Search
Madhuri97/project-1-105 pull request #7
Opened 2020-04-27 14:45 UTC by Madhuri97

Completed Search feature

2020-04-27 19:04 UTC, ChaitanyaPuritipati requested changes
1. Work is good and also your UI looks good as I have seen during the stand up meetings

1. There quite few changes required apart from the comments mentioned below, one change is to use commonly used content is HTML tags, links, body tags etc.. in a separate HTML file and extend them into every file. This reduces the burden of writing same lines again and again

1. Try writing comments for the code. For example, you can write Navbar code starts here and write ends here at the place where it ends. This makes it easier to refer to the code again

2020-04-27 19:04 UTC, ChaitanyaPuritipati commented on project1/templates/Registration.html
>              <form action="http://localhost:5000/register" method = "POST">
Can remove http://localhost:5000 from the code. We can sometimes change the server port. So if we do that, you need to update the frontend code which is hectic

2020-04-27 19:04 UTC, ChaitanyaPuritipati commented on project1/templates/login.html
> +
Try putting these styles in seperate css file and let me know if it works or not. Ideally this looks more clumsy

2020-04-27 19:04 UTC, ChaitanyaPuritipati commented on project1/templates/login.html
> +            <form class="example" action="/action_page.php" style="margin:auto;max-width:700px" method = 'POST'>
You need to either use action for form or formation for button if you have only single submit, And also action_page.php is not doing any work. You can remove it

2020-04-27 19:04 UTC, ChaitanyaPuritipati commented on project1/templates/login.html
> +        {% if formaction == '/home'  %}
Here you could have compared with booksdata. That looks better than comparing with the URL string

2020-04-27 19:04 UTC, ChaitanyaPuritipati commented on project1/templates/login.html
> +        {% if message1 %}
Can keep this message as error message instead of messages. It will be meaningful for a third person when he/she reads it

2020-04-28 11:14 UTC, Madhuri97 commented on project1/templates/login.html
> +            <form class="example" action="/action_page.php" style="margin:auto;max-width:700px" method = 'POST'>
Done

2020-04-28 11:14 UTC, Madhuri97 commented on project1/templates/login.html
> +        {% if message1 %}
done

2020-04-29 13:10 UTC, ChaitanyaPuritipati requested changes

2020-04-29 13:10 UTC, ChaitanyaPuritipati commented on project1/templates/Registration.html
> +            <form>
You should only remove http://localhost:5000. rest all should be there. <form action = "/register" method = "POST">

2020-04-29 13:10 UTC, ChaitanyaPuritipati commented on project1/templates/Registration.html
>                  <button type="submit" class="btn btn-primary" formaction = "http://127.0.0.1:5000/authen"><b>Login</b></button>
Here as well, it should be formaction = "/authen"

2020-04-29 13:49 UTC, ChaitanyaPuritipati approved these changes
Good work

2020-04-29 13:49 UTC, merged